name: hsm

networks:
  hsm-network:
    name: hsm-network
    driver: bridge

services:
  hsm-app-be-main:
    image: hsm-app-be-main
    build:
      context: ../
      args:
        - APP_TYPE=main
      dockerfile: ./docker/dockerFile.dev
    container_name: hsm-app-be-main
    ports:
      - "3000:3000"
    networks:
      - hsm-network
    env_file:
      - ../.env
    volumes:
      - ../:/app
      - /app/node_modules
    environment:
      SECRET_PATH: /app/be
    restart: unless-stopped
    depends_on:
      - hsm-app-db-postgres
      - hsm-app-db-redis
      - hsm-app-be-worker

  hsm-app-be-worker:
    image: hsm-app-be-worker
    build:
      context: ../
      args:
        - APP_TYPE=worker
      dockerfile: ./docker/dockerFile.dev
    container_name: hsm-app-be-worker
    networks:
      - hsm-network
    env_file:
      - ../.env
    volumes:
      - ../:/app
      - /app/node_modules
    environment:
      SECRET_PATH: /app/be
    restart: unless-stopped
    depends_on:
      - hsm-app-db-postgres
      - hsm-app-db-redis

  hsm-app-db-postgres:
    image: postgres:17-bookworm
    container_name: hsm-app-db-postgres
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - hsm-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hsm
    volumes:
      - ./postgres/init-schemas.sql:/docker-entrypoint-initdb.d/postgres.schemas.sql:ro
    restart: unless-stopped
    healthcheck:
      test: [CMD-SHELL, pg_isready -U postgres -d hsm]
      interval: 5s
      timeout: 3s
      retries: 20
    #depends_on:
    #  - pgadmin
  hsm-app-db-redis:
    image: redis:8-bookworm
    container_name: hsm-app-db-redis
    command: [redis-server, /usr/local/etc/redis/redis.conf]
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./redis/users.acl:/usr/local/etc/redis/users.acl:ro
    ports:
      - "6379:6379"
    networks:
      - hsm-network
    restart: unless-stopped
    environment:
      REDIS_USER: redis
      REDIS_PASSWORD: redis
    healthcheck:
      test: [CMD, redis-cli, -a, redis, ping]
      interval: 5s
      timeout: 3s
      retries: 20
    #depends_on:
    #  - redisinsight

  hsm-app-db-minio:
    image: minio/minio:latest
    container_name: hsm-app-db-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - hsm-network
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    restart: unless-stopped

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - '5540:5540'
    networks:
      - hsm-network
    environment:
      RI_ACCEPT_TERMS_AND_CONDITIONS: true
      RI_REDIS_HOST: hsm-app-db-redis
      RI_REDIS_PORT: 6379
      RI_REDIS_USERNAME: redis
      RI_REDIS_PASSWORD: redis
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - '5050:80'
    networks:
      - hsm-network
