api:
  dashboard: true
  insecure: true

log:
  level: INFO

entryPoints:
  web:
    address: ":80"
  hsm-app-be-main:
    address: ":3000"
  hsm-app-db-postgres:
    address: ":5432"
  hsm-app-db-redis:
    address: ":6379"
  hsm-app-db-minio-api:
    address: ":9000"
  hsm-app-db-minio-console:
    address: ":9001"
  pgadmin:
    address: ":5050"
  redisinsight:
    address: ":5540"

providers:
  docker:
    exposedByDefault: false
